### ISSUE TITLE
Reminduck Flatpak not working on Ubuntu 21.04

### ISSUE THREAD

**Issue by manikandancode** [flathub/com.github.matfantinel.reminduck#5]
Plz check
![Screenshot from 2021-08-18 11-37-22](https://user-images.githubusercontent.com/46480489/129866913-804232fb-d50c-4302-aa76-618e45aef984.png)
![Screenshot from 2021-08-18 11-41-33](https://user-images.githubusercontent.com/46480489/129867034-b66d3f42-e216-45c6-b623-a1c98be7bc52.png)

**Comment by matfantinel** [comment]
Hi @manikandancode , sorry for this. I just pushed the fix to Flathub via  #6 , it should be up in a few minutes.
